

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mysql://localhost:3306/testdb
    username: rorot
    password: Osan2051102!

  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: true

